SELECT * FROM [dbo].[TR_OPTIMIZACION_AUTO_SCRIPT]
DELETE FROM [dbo].[TR_OPTIMIZACION_AUTO_SCRIPT] where ID > 610
Select TOP 1 ID FROM TR_OPTIMIZACION_AUTO_SCRIPT ORDER BY ID DESC
SELECT * FROM [dbo].[TR_QUERY_VERTICAL] 