IF OBJECT_ID(N'TR_QUERY_VERTICAL', N'U') IS NULL
CREATE TABLE TR_QUERY_VERTICAL(
	IdQuery INT NOT NULL,
	IdVertical INT NOT NULL
);

IF OBJECT_ID(N'TR_OPTIMIZACION_AUTO_TIPO_SCRIPT', N'U') IS NULL
CREATE TABLE TR_OPTIMIZACION_AUTO_TIPO_SCRIPT(
	ID INT IDENTITY(1,1) NOT NULL,
	TIPO NVARCHAR (100) NOT NULL,
	ID_GRUPO INT NOT NULL,
 CONSTRAINT PK_TR_AUTO_TIPO_SCRIPT PRIMARY KEY(ID),
 CONSTRAINT FK_TR_AUTO_TIPO_SCRIPT FOREIGN KEY(ID) REFERENCES TR_OPTIMIZACION_AUTO_TIPO_SCRIPT
 )

IF OBJECT_ID(N'TR_OPTIMIZACION_AUTO_SCRIPT', N'U') IS NULL
CREATE TABLE TR_OPTIMIZACION_AUTO_SCRIPT(
	ID int IDENTITY(1,1) NOT NULL,
	NOMBRE_PROCEDIMIENTO varchar(max) NOT NULL,
	ID_TIPO_SCRIPT int NOT NULL,
	CONSULTA_SEL nvarchar(max) NULL,
	PARAM_SEL nvarchar(max) NULL,
	REGULARIZA BIT NULL,
	CONSULTA_REG nvarchar(max) NULL,
	PARAM_REG nvarchar(max) NULL,
 CONSTRAINT PK_TR_OPTIMIZACION_AUTO_SCRIPT PRIMARY KEY(ID)
);

IF OBJECT_ID(N'TR_VERTICAL', N'U') IS NULL
CREATE TABLE TR_VERTICAL(
	Id INT NOT NULL,
	Vertical VARCHAR(255) NOT NULL
);

